##### Accessing Data with Pandas

In [16]:
import pandas as pd
coffee = pd.read_csv('./coffee.CSV')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [18]:
coffee.tail(2)

       Day Coffee Type  Units Sold
12  Sunday    Espresso          45
13  Sunday       Latte          35

In [22]:
coffee.sample(5) # Random Access

         Day Coffee Type  Units Sold
12    Sunday    Espresso          45
6   Thursday    Espresso          40
10  Saturday    Espresso          45
11  Saturday       Latte          35
7   Thursday       Latte          30

In [62]:
coffee.sample(10, random_state=42)  # Specific value

          Day Coffee Type  Units Sold
9      Friday       Latte          35
11   Saturday       Latte          35
0      Monday    Espresso          25
12     Sunday    Espresso          45
5   Wednesday       Latte          25
8      Friday    Espresso          45
2     Tuesday    Espresso          30
1      Monday       Latte          15
13     Sunday       Latte          35
4   Wednesday    Espresso          35

In [29]:
display(coffee) # Display complete  data set

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

##### Accessing specific value

In [66]:
coffee.loc[0] # Specific value

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [70]:
coffee.loc[[0,1,5]] # Multiple rows

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
5  Wednesday       Latte          25

In [73]:
coffee[0:3] # To access part of the rows

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [75]:
coffee.loc[5:8, ["Day"]] # Accees only days from 5ht to 8th rows

         Day
5  Wednesday
6   Thursday
7   Thursday
8     Friday

In [79]:
coffee.loc[9:, ["Day","Units Sold"]] # Access all days and units sold of all rows, :->all the rows

         Day  Units Sold
9     Friday          35
10  Saturday          45
11  Saturday          35
12    Sunday          45
13    Sunday          35

In [87]:
coffee.iloc[:5,[0,2]] # or access column wise through index

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [101]:
coffee.index=coffee["Day"]  # changes the index of the df
coffee.loc['Monday']  # Get all data from monday

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [137]:
coffee.iloc[1:4, coffee.columns.get_loc("Units Sold")] = 10
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          10
Tuesday      Tuesday    Espresso          10
Tuesday      Tuesday       Latte          10
Wednesday  Wednesday    Espresso          35

In [118]:
coffee["Day"]

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
Name: Day, dtype: object

In [119]:
coffee.Day

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
Name: Day, dtype: object

In [130]:
coffee.sort_values( "Units Sold") # Increasing order

                 Day Coffee Type  Units Sold
Day
Monday        Monday       Latte          10
Tuesday      Tuesday    Espresso          10
Tuesday      Tuesday       Latte          10
Monday        Monday    Espresso          25
Wednesday  Wednesday       Latte          25
Thursday    Thursday       Latte          30
Wednesday  Wednesday    Espresso          35
Friday        Friday       Latte          35
Sunday        Sunday       Latte          35
Saturday    Saturday       Latte          35
Thursday    Thursday    Espresso          40
Friday        Friday    Espresso          45
Saturday    Saturday    Espresso          45
Sunday        Sunday    Espresso          45

In [141]:
coffee.sort_values("Units Sold").iloc[10] # Specific items

Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: Thursday, dtype: object

In [140]:
coffee.iloc[0:5].sort_values("Units Sold") # Only sort first 5 indexs

                 Day Coffee Type  Units Sold
Day
Monday        Monday       Latte          10
Tuesday      Tuesday    Espresso          10
Tuesday      Tuesday       Latte          10
Monday        Monday    Espresso          25
Wednesday  Wednesday    Espresso          35

In [146]:
coffee.sort_values( "Units Sold", ascending=False) # Ascending order

                 Day Coffee Type  Units Sold
Day
Saturday    Saturday    Espresso          45
Friday        Friday    Espresso          45
Sunday        Sunday    Espresso          45
Thursday    Thursday    Espresso          40
Wednesday  Wednesday    Espresso          35
Saturday    Saturday       Latte          35
Sunday        Sunday       Latte          35
Friday        Friday       Latte          35
Thursday    Thursday       Latte          30
Monday        Monday    Espresso          25
Wednesday  Wednesday       Latte          25
Tuesday      Tuesday    Espresso          10
Monday        Monday       Latte          10
Tuesday      Tuesday       Latte          10

In [156]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=[0,1])  # Ascending order of coffee type

                 Day Coffee Type  Units Sold
Day
Friday        Friday    Espresso          45
Saturday    Saturday    Espresso          45
Sunday        Sunday    Espresso          45
Thursday    Thursday    Espresso          40
Wednesday  Wednesday    Espresso          35
Friday        Friday       Latte          35
Saturday    Saturday       Latte          35
Sunday        Sunday       Latte          35
Thursday    Thursday       Latte          30
Monday        Monday    Espresso          25
Wednesday  Wednesday       Latte          25
Tuesday      Tuesday    Espresso          10
Monday        Monday       Latte          10
Tuesday      Tuesday       Latte          10

In [158]:
# Using for loop
for index, row in coffee.iterrows():
    print(index)
    print(row['Units Sold'])
    print("\n")

Monday
25


Monday
10


Tuesday
10


Tuesday
10


Wednesday
35


Wednesday
25


Thursday
40


Thursday
30


Friday
45


Friday
35


Saturday
45


Saturday
35


Sunday
45


Sunday
35