### Merging and Concatenating data

In [5]:
import pandas as pd
bois = pd.read_csv('./bios.CSV')
bois.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [7]:
nocs = pd.read_csv('./noc_regions.CSV')
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [13]:
# combines (joins) two DataFrames using matching country codes
bois_new = pd.merge( bois, nocs, left_on = 'born_country', right_on = 'NOC', how='left')
bois_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [15]:
bois_new.rename(columns = {'region':'born_country_full'}, inplace=True)
bois_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [23]:
# filters and shows rows where NOC_x and born_country_full values are different.
bois_new[bois_new['NOC_x'] != bois_new['born_country_full']]
bois_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,NaN,NaN,NaN
13,14,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN,MAR,Morocco,NaN
27,28,"Guy, Baron Lejeune",NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# It shows the name, NOC_x, and born_country_full for rows where NOC_x and born_country_full are different
bois_new[bois_new['NOC_x'] != bois_new['born_country_full']][['name','NOC_x','born_country_full']]
bois_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,NaN,NaN,NaN
13,14,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN,MAR,Morocco,NaN
27,28,"Guy, Baron Lejeune",NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# collect rows whos born in usa and gbr
usa = bois[bois['born_country'] == 'USA'].copy()
gbr = bois[bois['born_country'] == 'GBR'].copy()

In [30]:
# create new df by combining above two df's
new_df = pd.concat([usa,gbr])
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN

In [34]:
results = pd.read_csv('./results.CSV')
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [36]:
# joins the results and bois DataFrames using the athlete_id column.
combined_df = pd.merge(results, bois, on='athlete_id',how='left')
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02

### Handling Null Values

In [37]:
coffee = pd.read_csv('./coffee.CSV')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [38]:
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   14 non-null     int64
dtypes: int64(1), object(2)
memory usage: 468.0+ bytes

In [46]:
import numpy as np
coffee.loc[[2,3], 'Units Sold'] = np.nan
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
2     Tuesday    Espresso         NaN
3     Tuesday       Latte         NaN
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [47]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
dtype: int64

In [48]:
coffee.fillna(1001)

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
2     Tuesday    Espresso      1001.0
3     Tuesday       Latte      1001.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [54]:
# Calculate the mean value values and place the null values
coffee.fillna(coffee['Units Sold'].mean())

          Day Coffee Type  Units Sold
0      Monday    Espresso   25.000000
1      Monday       Latte   15.000000
2     Tuesday    Espresso   34.166667
3     Tuesday       Latte   34.166667
4   Wednesday    Espresso   35.000000
5   Wednesday       Latte   25.000000
6    Thursday    Espresso   40.000000
7    Thursday       Latte   30.000000
8      Friday    Espresso   45.000000
9      Friday       Latte   35.000000
10   Saturday    Espresso   45.000000
11   Saturday       Latte   35.000000
12     Sunday    Espresso   45.000000
13     Sunday       Latte   35.000000

In [56]:
coffee['Units Sold'].interpolate()

0     25.000000
1     15.000000
2     21.666667
3     28.333333
4     35.000000
5     25.000000
6     40.000000
7     30.000000
8     45.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [59]:
coffee['Units Sold'] = coffee['Units Sold'].interpolate()
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso   25.000000
1     Monday       Latte   15.000000
2    Tuesday    Espresso   21.666667
3    Tuesday       Latte   28.333333
4  Wednesday    Espresso   35.000000

In [60]:
coffee.dropna()

          Day Coffee Type  Units Sold
0      Monday    Espresso   25.000000
1      Monday       Latte   15.000000
2     Tuesday    Espresso   21.666667
3     Tuesday       Latte   28.333333
4   Wednesday    Espresso   35.000000
5   Wednesday       Latte   25.000000
6    Thursday    Espresso   40.000000
7    Thursday       Latte   30.000000
8      Friday    Espresso   45.000000
9      Friday       Latte   35.000000
10   Saturday    Espresso   45.000000
11   Saturday       Latte   35.000000
12     Sunday    Espresso   45.000000
13     Sunday       Latte   35.000000

In [62]:
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold
0      Monday    Espresso   25.000000
1      Monday       Latte   15.000000
2     Tuesday    Espresso   21.666667
3     Tuesday       Latte   28.333333
4   Wednesday    Espresso   35.000000
5   Wednesday       Latte   25.000000
6    Thursday    Espresso   40.000000
7    Thursday       Latte   30.000000
8      Friday    Espresso   45.000000
9      Friday       Latte   35.000000
10   Saturday    Espresso   45.000000
11   Saturday       Latte   35.000000
12     Sunday    Espresso   45.000000
13     Sunday       Latte   35.000000