#### Adding and Removing Columns

In [112]:
import pandas as pd
coffee = pd.read_csv('./coffee.CSV')
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [115]:
coffee ['price']=4.99 # Add price columns
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [117]:
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [128]:
import numpy as np
coffee['new_price'] = np.where(coffee['Coffee Type']=='Espresso', 3.99, 5.99) 
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [132]:
coffee[['Day', 'Coffee Type','new_price']] # Access specific columns

          Day Coffee Type  new_price
0      Monday    Espresso       3.99
1      Monday       Latte       5.99
2     Tuesday    Espresso       3.99
3     Tuesday       Latte       5.99
4   Wednesday    Espresso       3.99
5   Wednesday       Latte       5.99
6    Thursday    Espresso       3.99
7    Thursday       Latte       5.99
8      Friday    Espresso       3.99
9      Friday       Latte       5.99
10   Saturday    Espresso       3.99
11   Saturday       Latte       5.99
12     Sunday    Espresso       3.99
13     Sunday       Latte       5.99

In [153]:
coffee.drop(columns=['new_price'])

          Day Coffee Type  Units Sold  revenue
0      Monday    Espresso          25    99.75
1      Monday       Latte          15    89.85
2     Tuesday    Espresso          30   119.70
3     Tuesday       Latte          20   119.80
4   Wednesday    Espresso          35   139.65
5   Wednesday       Latte          25   149.75
6    Thursday    Espresso          40   159.60
7    Thursday       Latte          30   179.70
8      Friday    Espresso          45   179.55
9      Friday       Latte          35   209.65
10   Saturday    Espresso          45   179.55
11   Saturday       Latte          35   209.65
12     Sunday    Espresso          45   179.55
13     Sunday       Latte          35   209.65

In [156]:
coffee['revenue'] = coffee['Units Sold']*coffee['new_price']
coffee # Multiplication of two rows

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       3.99   119.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

In [162]:
coffee.rename(columns={'new_price':'price'}) # to change the name of the columns

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [166]:
bois = pd.read_csv('./bios.csv')
bois.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [167]:
bois_new = bois.copy()

In [170]:
# creates a new column called first_name in the DataFrame bois_new by extracting the first word from the name column
bois_new['first_name'] = bois_new['name'].str.split(' ').str[0]
bois_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [176]:
bois_new.query('first_name == "Keith"') # access name start from Keith

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

In [177]:
bois_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
 10  first_name    145500 non-null  object
dtypes: float64(2), int64(1), object(8)
memory usage: 12.2+ MB

In [190]:
# converts the born_date column into a proper datetime format and stores it in a new column born_datetime.
bois_new['born_datetime'] = pd.to_datetime(bois_new['born_date'])
bois_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15

In [189]:
bois_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  first_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 13.3+ MB

In [202]:
bois_new['born_year'] = bois_new['born_datetime'].dt.year
bois_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30,2002.0
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20,1999.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08,1998.0
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19,1899.0
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15,1913.0

In [203]:
bois_new[['name','born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [209]:
bois_new.to_csv('./bois.csv', index=False)

In [215]:
bois['height_category'] = bois['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x < 185 else "Tall"))
bois.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [218]:
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'heightweight'
    elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
        return 'Middleweight'
    else:
        return 'Heavyweight'

bois['category'] = bois.apply(categorize_athlete, axis=1)

bois.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,heightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight