### Aggregating Data

In [5]:
import pandas as pd
bois = pd.read_csv('./bios.CSV')
bois.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [6]:
bois['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Kirovgrad             1
Pereiaslav            1
Podgornyy             1
Kudepsta              1
Furmanov              1
Name: count, Length: 22368, dtype: int64

In [7]:
bois[bois['born_country'] == 'USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Massachusetts            530
Pennsylvania             530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [8]:
coffee = pd.read_csv('./coffee.CSV')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

##### Group by functions in pandas

In [12]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [13]:
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [19]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum'})

                       Units Sold
Coffee Type Day
Espresso    Friday             45
            Monday             25
            Saturday           45
            Sunday             45
            Thursday           40
            Tuesday            30
            Wednesday          35
Latte       Friday             35
            Monday             15
            Saturday           35
            Sunday             35
            Thursday           30
            Tuesday            20
            Wednesday          25

##### Pivot Table

In [23]:
pivot = coffee.pivot(columns='Coffee Type', index='Day')
pivot.sum()

            Coffee Type
Units Sold  Espresso       265
            Latte          195
dtype: int64

In [24]:
pivot.sum(axis=1)

Day
Friday       80
Monday       40
Saturday     80
Sunday       80
Thursday     70
Tuesday      50
Wednesday    60
dtype: int64

##### Using DateTime with Groupby

In [30]:
bois['born_date'] = pd.to_datetime(bois['born_date'])
bois['month_born'] = bois['born_date'].dt.month
bois['year_born'] = bois['born_date'].dt.year
bois.groupby([bois['year_born'],bois['month_born']])['name'].count().reset_index().sort_values('name', ascending=False)

      year_born  month_born  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]

#### Advanced Functionality

In [ ]:
# shift() rank() cumsum() rolling()

In [39]:
coffee['yesterday_revenue'] = coffee['Units Sold'].shift(2)
coffee

          Day Coffee Type  Units Sold  yesterday_revenue
0      Monday    Espresso          25                NaN
1      Monday       Latte          15                NaN
2     Tuesday    Espresso          30               25.0
3     Tuesday       Latte          20               15.0
4   Wednesday    Espresso          35               30.0
5   Wednesday       Latte          25               20.0
6    Thursday    Espresso          40               35.0
7    Thursday       Latte          30               25.0
8      Friday    Espresso          45               40.0
9      Friday       Latte          35               30.0
10   Saturday    Espresso          45               45.0
11   Saturday       Latte          35               35.0
12     Sunday    Espresso          45               45.0
13     Sunday       Latte          35               35.0

In [41]:
coffee['pct_change'] = coffee['Units Sold'] / coffee['yesterday_revenue']
coffee

          Day Coffee Type  Units Sold  yesterday_revenue  pct_change
0      Monday    Espresso          25                NaN         NaN
1      Monday       Latte          15                NaN         NaN
2     Tuesday    Espresso          30               25.0    1.200000
3     Tuesday       Latte          20               15.0    1.333333
4   Wednesday    Espresso          35               30.0    1.166667
5   Wednesday       Latte          25               20.0    1.250000
6    Thursday    Espresso          40               35.0    1.142857
7    Thursday       Latte          30               25.0    1.200000
8      Friday    Espresso          45               40.0    1.125000
9      Friday       Latte          35               30.0    1.166667
10   Saturday    Espresso          45               45.0    1.000000
11   Saturday       Latte          35               35.0    1.000000
12     Sunday    Espresso          45               45.0    1.000000
13     Sunday       Latte          35               35.0    1.000000

In [33]:

latte = coffee[coffee['Coffee Type']=="Latte"].copy()
latte['3day'] = latte['Units Sold'].rolling(3).sum()

In [34]:

latte

          Day Coffee Type  Units Sold   3day
1      Monday       Latte          15    NaN
3     Tuesday       Latte          20    NaN
5   Wednesday       Latte          25   60.0
7    Thursday       Latte          30   75.0
9      Friday       Latte          35   90.0
11   Saturday       Latte          35  100.0
13     Sunday       Latte          35  105.0

In [43]:
!pip install pyjanitor

Collecting pyjanitor
  Downloading pyjanitor-0.32.20-py3-none-any.whl.metadata (3.7 kB)
Collecting natsort<9,>=8.4.0 (from pyjanitor)
  Downloading natsort-8.4.0-py3-none-any.whl.metadata (21 kB)
Collecting pandas-flavor<0.9,>=0.8.1 (from pyjanitor)
  Downloading pandas_flavor-0.8.1-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: multipledispatch in c:\users\thris\anaconda3\lib\site-packages (from pyjanitor) (0.6.0)
Requirement already satisfied: scipy in c:\users\thris\anaconda3\lib\site-packages (from pyjanitor) (1.15.3)
Collecting janitor-rs<0.7,>=0.6.1 (from pyjanitor)
  Downloading janitor_rs-0.6.1-cp313-cp313-win_amd64.whl.metadata (281 bytes)
Requirement already satisfied: pandas>=0.23 in c:\users\thris\anaconda3\lib\site-packages (from pandas-flavor<0.9,>=0.8.1->pyjanitor) (2.2.3)
Requirement already satisfied: xarray in c:\users\thris\anaconda3\lib\site-packages (from pandas-flavor<0.9,>=0.8.1->pyjanitor) (2025.4.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\thris\anaconda3\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\thris\anaconda3\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\thris\anaconda3\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\thris\anaconda3\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\thris\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (1.17.0)
Requirement already satisfied: packaging>=23.2 in c:\users\thris\anaconda3\lib\site-packages (from xarray->pandas-flavor<0.9,>=0.8.1->pyjanitor) (24.2)
Downloading pyjanitor-0.32.20-py3-none-any.whl (277 kB)
Downloading janitor_rs-0.6.1-cp313-cp313-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.5 MB 1.2 MB/s eta 0:00:01
   ------------- -------------------------- 0.5/1.5 MB 1.2 MB/s eta 0:00:01
   -------------------- ------------------- 0.8/1.5 MB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.5 MB 1.1 MB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 1.2 MB/s eta 0:00:00
Downloading natsort-8.4.0-py3-none-any.whl (38 kB)
Downloading pandas_flavor-0.8.1-py3-none-any.whl (8.5 kB)
Installing collected packages: natsort, janitor-rs, pandas-flavor, pyjanitor

   ---------- ----------------------------- 1/4 [janitor-rs]
   ------------------------------ --------- 3/4 [pyjanitor]
   ------------------------------ --------- 3/4 [pyjanitor]
   ------------------------------ --------- 3/4 [pyjanitor]
   ------------------------------ --------- 3/4 [pyjanitor]
   ------------------------------ --------- 3/4 [pyjanitor]
   ------------------------------ --------- 3/4 [pyjanitor]
   ------------------------------ --------- 3/4 [pyjanitor]
   ------------------------------ --------- 3/4 [pyjanitor]
   ------------------------------ --------- 3/4 [pyjanitor]
   ------------------------------ --------- 3/4 [pyjanitor]
   ---------------------------------------- 4/4 [pyjanitor]

Successfully installed janitor-rs-0.6.1 natsort-8.4.0 pandas-flavor-0.8.1 pyjanitor-0.32.20

In [61]:

results = pd.read_csv('./results.CSV')
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [3]:
import pandas as pd
results_numpy = pd.read_csv('./results.CSV')
results_arrow = pd.read_csv('./results.CSV',engine='pyarrow',dtype_backend='pyarrow')

In [4]:
results_numpy.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [5]:
results_numpy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  object
 2   discipline  308407 non-null  object
 3   event       308408 non-null  object
 4   as          308408 non-null  object
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  object
 7   team        121714 non-null  object
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 23.8+ MB

In [6]:
results_arrow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  double[pyarrow]
 1   type        305807 non-null  string[pyarrow]
 2   discipline  308407 non-null  string[pyarrow]
 3   event       308408 non-null  string[pyarrow]
 4   as          308408 non-null  string[pyarrow]
 5   athlete_id  308408 non-null  int64[pyarrow]
 6   noc         308407 non-null  string[pyarrow]
 7   team        121714 non-null  string[pyarrow]
 8   place       283193 non-null  double[pyarrow]
 9   tied        308408 non-null  bool[pyarrow]
 10  medal       44139 non-null   string[pyarrow]
dtypes: bool[pyarrow](1), double[pyarrow](2), int64[pyarrow](1), string[pyarrow](7)
memory usage: 37.5 MB

In [7]:
results_numpy["as"].str.contains("Keith")

0         False
1         False
2         False
3         False
4         False
          ...
308403    False
308404    False
308405    False
308406    False
308407    False
Name: as, Length: 308408, dtype: bool